#pragma once

enum class INPUT_ID
{
	BUTTON_LEFT,
	BUTTON_UP,
	BUTTON_RIGHT,
	BUTTON_DOWN,
	BUTTON_ATTACK,
	BUTTON_ROTA_R,
	BUTTON_MENU,			// ÉÅÉjÉÖÅ[Ç⁄ÇΩÇÒ
	BUTTON_MOVEON,			// éüÇ…êiÇﬁ
	BUTTON_RETURN,			// ñﬂÇÈ
	BUTTON_NUM_0,
	BUTTON_NUM_1,
	BUTTON_NUM_2,
	BUTTON_NUM_3,
	BUTTON_NUM_4,
	BUTTON_NUM_5,
	BUTTON_NUM_6,
	BUTTON_NUM_7,
	BUTTON_NUM_8,
	BUTTON_NUM_9,
	BUTTON_NUM_DOT,
	BUTTON_NUM_ENTER,
	MAX,
};

INPUT_ID begin(INPUT_ID);
INPUT_ID end(INPUT_ID);
INPUT_ID operator++(INPUT_ID& key);
INPUT_ID operator*(INPUT_ID key);